https://www.learnpytorch.io/
https://github.com/mrdbourke/pytorch-deep-learning/tree/main

### creating a tensor

In [32]:
import torch
scalar = torch.tensor(7)
print(scalar.item())
print(scalar.ndim)

vector = torch.tensor([7,7])
print(vector.ndim)
print(vector.shape)

Matrix = torch.tensor([[7, 7], [7, 7]])
print(Matrix.ndim)
print(Matrix.shape)

tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor1.ndim)
print(tensor1.shape)

tensor2 = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]) # 1 3x3 tensor
# first square bracket has 1 element, next square bracket has 3 elements then the last sq bracket has 3 elements
print(tensor2.ndim)
print(tensor2.shape)

7
0
1
torch.Size([2])
2
torch.Size([2, 2])
2
torch.Size([3, 3])
3
torch.Size([1, 3, 3])


In [33]:
#random tensors
random_tensors = torch.rand(2,3)
print(random_tensors)

#zeros tensors
zeros_tensors = torch.zeros(2,3)
print(zeros_tensors)

#ones tensors
ones_tensors = torch.ones(2,3)
print(ones_tensors)

print(random_tensors.dtype)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [34]:
# range
range_tensor = torch.arange(0, 10, step=2)
print(range_tensor)

# tensor likes
# creating a tensor with the same shape as another tensor
zero_tensor = torch.zeros_like(range_tensor)
print(zero_tensor)

tensor([0, 2, 4, 6, 8])
tensor([0, 0, 0, 0, 0])


### Tensor Data Types
**Note:** Tensor datatypes is one of the 3 bit errors that one can run into
1. Tensors not right datatype (float32, float64 etc) ->tensor.dtype
2. Tensors not right shape (different tensor shapes) -> tensor.shape
3. Tensors not on the right device (cuda,cpu etc) -> tensor.device

In [35]:
#float 32 tensor
float_32_tensor = torch.tensor([1.0, 2.0, 3.0], 
                               dtype=None, #what datatype is the tensor
                               device = None, # which device the tensor is running on
                               requires_grad=False #whether or not track gradients with this tensor operations
                               )
#torch.float32 is the default

#float 16 tensor
# float_16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)
float_16_tensor = float_32_tensor.type(torch.float16)  # Converting to float16
print(float_16_tensor)
print((float_16_tensor*float_32_tensor).dtype)
# even multiplying with int64 will work
#but if you multiply with long tensor, it will not work because long tensor is not compatible with float16

tensor([1., 2., 3.], dtype=torch.float16)
torch.float32


### Manipulating Tensors(tensor operations)
Tensor operations include:-
1. Addition
2. Subtraction
3. Multiplication(element-wise)
4. Division
5. Matrix multiplication

In [36]:
#Multiplcation
tensor = torch.tensor([1,2,3])
print(tensor*10)
print(torch.mul(tensor,10))

#Addition
print(tensor+10)
print(torch.add(tensor,10))

#Subtraction
print(tensor-10)
print(torch.sub(tensor,10))

tensor([10, 20, 30])
tensor([10, 20, 30])
tensor([11, 12, 13])
tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([-9, -8, -7])


In [37]:
#Matrix multiplication
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
print(torch.matmul(tensor1,tensor2))

tensor(32)


In [38]:
t1 = torch.tensor([[1, 2], [3, 4]])
t2 = torch.tensor([[5, 6], [7, 8]])
print(torch.mm(t1, t2))  #mm is an alias for matmul for 2D tensors

tensor([[19, 22],
        [43, 50]])


### Matrix multiplication (is all you need)
- One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

- PyTorch implements matrix multiplication functionality in the torch.matmul() method.

- The main two rules for matrix multiplication to remember are:

@- matrix multiplication operator(tensor @ tensor)
1. The inner dimensions must match:
-  (3, 2) @ (3, 2) won't work
-  (2, 3) @ (3, 2) will work
-  (3, 2) @ (2, 3) will work
2. The resulting matrix has the shape of the outer dimensions:
-  (2, 3) @ (3, 2) -> (2, 2)
-  (3, 2) @ (2, 3) -> (3, 3)

In [39]:
torch.matmul(torch.rand(10,7),torch.rand(7,10)) # 10x7 matrix with 7x10 matrix -> 10x10 matrix


tensor([[1.3193, 0.7765, 1.7062, 1.0895, 1.6610, 0.7652, 1.0255, 0.9517, 1.3405,
         1.1156],
        [1.0402, 0.7098, 1.4274, 0.7257, 1.6188, 0.5116, 0.8084, 0.8872, 1.3602,
         1.1503],
        [2.3015, 1.4535, 2.9171, 1.7673, 2.6363, 1.6448, 1.7183, 1.3784, 2.5141,
         1.7234],
        [2.1607, 1.1591, 2.6680, 1.7352, 2.0026, 1.4422, 1.4839, 1.2560, 1.7148,
         1.2586],
        [0.8014, 0.8342, 1.7460, 1.2356, 1.7887, 0.8597, 0.8101, 0.7719, 1.6226,
         0.8155],
        [1.8278, 1.4250, 2.8927, 1.8118, 2.6533, 1.5351, 1.3642, 1.3966, 2.3745,
         1.4627],
        [2.0459, 1.0451, 2.6293, 1.5135, 1.8756, 1.2633, 1.5923, 0.9979, 2.0645,
         1.2632],
        [1.7256, 1.0230, 2.2007, 1.1701, 1.7688, 1.0640, 1.0457, 1.1548, 1.5068,
         1.1726],
        [1.6902, 0.8300, 1.9605, 0.9836, 1.4417, 0.8637, 1.0503, 1.0140, 1.2750,
         1.1023],
        [1.4962, 0.8031, 1.9311, 1.3192, 1.7915, 0.8193, 1.1605, 1.0326, 1.3608,
         1.1140]])

### Transpose

In [40]:
tensor3 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor3.T)  # Transpose of a 2D tensor
print(torch.transpose(tensor3, 1, 1))  # Transpose of a 2D tensor with specified dimensions

tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


### min,max,mean, sum etc (tensor aggregation)

In [41]:
x = torch.arange(0,100,10)

#Find min
print(x.min(),torch.min(x))  # Minimum value in the tensor

#Find max
print(x.max(), torch.max(x))  # Maximum value in the tensor

#Find mean
# print(x.mean()) this will not work since x is of long int 64 datatype
print(torch.mean(x.type(torch.float32)), x.type(torch.float32).mean())  # Mean value of the tensor

#Find sum
print(x.sum(), torch.sum(x))  # Sum of all elements in the tensor

tensor(0) tensor(0)
tensor(90) tensor(90)
tensor(45.) tensor(45.)
tensor(450) tensor(450)


### Finding positional min and max

In [42]:
print(x.argmin()) #minimum occurs at 0th index
print(x.argmax()) #maximum occurs at 9th index

tensor(0)
tensor(9)


### Reshaping, stacking, squeezing and unsqueezing
Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:
                                    
1) torch.reshape(input, shape)	    
Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().

2) Tensor.view(shape)	            
Returns a view of the original tensor in a different shape but shares the same data as the original tensor.

3) torch.stack(tensors, dim=0)	    
Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.

4) torch.squeeze(input)	        
Squeezes input to remove all the dimenions with value 1.

5) torch.unsqueeze(input, dim)	    
Returns input with a dimension value of 1 added at dim.

6) torch.permute(input, dims)	    
Returns a view of the original input with its dimensions permuted (rearranged) to dims.


In [43]:
#Reshaping tensor
torch1 = torch.arange(1.,10,); # Size = (9)
# torch1.reshape(1,7) -> INVALID trying to reshape to a shape that is not compatible
torch1_reshaped = torch1.reshape(3,3)  # Reshape to 3x3 tensor
print(torch1_reshaped)
print(torch1)


tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [44]:
#Viewing the tensor
z = torch1.view(3,3)  # View the tensor as 3x3
print(z)
z[:,0] = 5  # Modify the first column
print(torch1)  # Original tensor is also modified since view creates a view of the original tensor
# Changing the shape using view doesnt reflect in the original tensor but changing the values in the view will reflect in the original tensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])


In [45]:
# Stack tensors
x = torch.arange(1, 10)
x_stacked = torch.stack([x, x, x], dim=0)  # Stack along the first dimension
print(x_stacked)
x_stacked_dim1 = torch.stack([x, x, x], dim=1)  # Stack along the second dimension
print(x_stacked_dim1)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])


torch.squeeze() (Squeezing the tensor to only have dimensions over 1).

In [46]:
#Squeeze
rand_tensor = torch.rand(1, 5)
print(rand_tensor)  # Random tensor with shape (1, 5)
print(rand_tensor.shape)
rand_tensor_squeezed = rand_tensor.squeeze()  # Remove dimensions of size 1
print(rand_tensor_squeezed)  # Squeezed tensor
print(rand_tensor_squeezed.shape)  # Shape after squeezing

tensor([[0.6625, 0.2297, 0.9545, 0.6099, 0.5643]])
torch.Size([1, 5])
tensor([0.6625, 0.2297, 0.9545, 0.6099, 0.5643])
torch.Size([5])


In [47]:
#Unsqueeze - adding a dimension
rand_tensor = torch.rand(5)  # Random tensor with shape (5,)
rand_tensor_unsqueezed_dim0 = rand_tensor.unsqueeze(dim=0)  # Add a dimension at the start
print(rand_tensor_unsqueezed_dim0)  # Unsqueezed tensor
print(rand_tensor_unsqueezed_dim0.shape)  # Shape after unsqueezing
rand_tensor_unsqueezed_dim1 = rand_tensor.unsqueeze(dim=1)  # Add a dimension at the second position
print(rand_tensor_unsqueezed_dim1)  # Unsqueezed tensor
print(rand_tensor_unsqueezed_dim1.shape)  # Shape after unsqueezing


tensor([[0.0594, 0.7099, 0.4250, 0.2709, 0.9295]])
torch.Size([1, 5])
tensor([[0.0594],
        [0.7099],
        [0.4250],
        [0.2709],
        [0.9295]])
torch.Size([5, 1])


In [48]:
#permute - changing the order of dimensions
# This is useful when you want to rearrange the dimensions of a tensor, for example, to change from (H, W, C) to (C, H, W) format.
# They share the same underlying data, so modifying one will affect the other.

# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

x_original[0, 0, 0] = 100  # Modify the original tensor
print(x_permuted[0, 0, 0])  # Access the modified value in the permuted tensor

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
tensor(100.)


In [49]:
#Indexing
x = torch.arange(1, 10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [50]:
x[0], x[0][0], x[0][0][0]  # Accessing the first element in the first row of the first channel

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [51]:
x[:,0], x[:,:,0], x[:,0,0]

#To get the middle column alone
x[:, :, 1]  # Accessing the middle column of the tensor

x[0,0,:] #Same as x[0][0]

tensor([1, 2, 3])

## Pytorch Tensors and NumPy

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

- torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
- torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

In [52]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Note: By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).

However, many PyTorch calculations default to using float32.

So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32).

Because we reassigned tensor above, if you change the tensor, the array stays the same.

In [53]:
#changing the value in the tensor will change the value in the numpy array
array[0] = 100.0  # Modify the numpy array
print(array)  # Modified numpy array
print(tensor)  
# To avoid chared memory u can create a copy by torch = torch.tensor(array)

[100.   2.   3.   4.   5.   6.   7.]
tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.], dtype=torch.float64)


In [54]:
#Tensor to NumPy array
tensor = torch.arange(1.0, 8.0)
array = tensor.numpy()  # Convert tensor to numpy array
tensor,array
# Changing the value in the tensor will change the value in the numpy array
tensor[0] = 100.0  # Modify the tensor
tensor,array

(tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.]),
 array([100.,   2.,   3.,   4.,   5.,   6.,   7.], dtype=float32))

### Reproducibility (trying to take the random out of random)
As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.

Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic (each step is predictable) so the randomness they create are simulated randomness (though there is debate on this too, but since I'm not a computer scientist, I'll let you find out more yourself).

How does this relate to neural networks and deep learning then?

We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

In short:

start with random numbers -> tensor operations -> try to make better (again and again and again)

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

So you can perform repeatable experiments.

For example, you create an algorithm capable of achieving X performance.

And then your friend tries it out to verify you're not crazy.

How could they do such a thing?

That's where reproducibility comes in.

In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?

Let's see a brief example of reproducibility in PyTorch.

We'll start by creating two random tensors, since they're random, you'd expect them to be different right?

In [55]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.2319, 0.2378, 0.2206, 0.4074],
        [0.9057, 0.4490, 0.6509, 0.7044],
        [0.5421, 0.0280, 0.4097, 0.2592]])

Tensor B:
tensor([[0.6951, 0.7100, 0.8263, 0.4353],
        [0.1437, 0.0200, 0.3165, 0.6236],
        [0.2279, 0.4962, 0.7377, 0.0042]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [59]:
# # Set the random seed
RANDOM_SEED=1 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])

Tensor D:
tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Device Agnostic code

In [64]:

device = "cpu" #defualt
tensor = torch.tensor([1, 2, 3],device=device)
print(tensor,device)
# Move tensor to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_gpu = tensor.to(device)
print(tensor_gpu, device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda


In [69]:
#If tensor in gpu cant transform to NumPy
# tensor_gpu.numpy()  # This will raise an error if tensor is on GPU
# To convert a GPU tensor to NumPy, first move it to CPU
tensor_cpu = tensor_gpu.cpu().numpy()  # Move tensor to CPU
tensor_cpu

array([1, 2, 3], dtype=int64)